### ISSUE TITLE
Issue less queries

### ISSUE THREAD

**Issue by morenoh149** [rathergood/Crypto-Currency-Price#9]
Hello.
I was wondering if there was a way to issue less queries in a sheet? I currently have several rows (currencies) and attribute queries (price, market_cap, available supply, total supply, 7d change and price_btc). That's 60 queries for my current portfolio of 10 currencies.

Thoughts?

**Comment by rathergood** [comment]
hmm....
right now, as you know, each query is an individual API request, regardless of if its for the same cryptocurrency. If you want all of the queries for a single crypto to be a single API call, then I would make each api call a request for the entire JSON, and parse each attribute into individual cells. I would then make another sheet, and get only the attributes you care about from the sheet that has ALL of the attributes.

The question is how to parse each attribute into individual cells...I don't know javascript/google script at all (it took me an embarrassingly long time to write this...), but it probably isn't too difficult. I'm pretty sure [this](http://blog.fastfedora.com/projects/import-json) works for this instead of using my code
